# Usamos una imagen oficial de Node
FROM node:20

# Establecemos el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiamos package.json y package-lock.json primero (para aprovechar cache de Docker)
COPY package*.json ./

# Instalamos dependencias
RUN npm install

# Copiamos el resto del proyecto
COPY . .

# Exponemos el puerto donde Vite corre
EXPOSE 5173

# Comando por defecto: modo desarrollo
CMD ["npm", "run", "dev", "--", "--host"]
