services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.env
    ports:
      - "5173:5173"   # puerto local:puerto contenedor
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
